import pathlib
from datetime import datetime

RESULTS_DIR = pathlib.Path("../results/immunefi_drafts")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

def generate_immunefi_draft(f):
    repo = f.get('repo', 'Unknown')
    conf = f.get('confidence', 0)
    bounty = f.get('bounty_estimate', 0)
    poc = f.get('synthesis', {}).get('exploit_poc', '// Proof of Concept / Remediation')
    
    report = (
        f"# Immunefi Vulnerability Report - {repo}\n\n"
        f"**Target Protocol**: {repo}\n"
        f"**AI Confidence**: {conf}%\n"
        f"**Estimated Bounty**: ${bounty:,}\n"
        f"**Detector Finding**: {f.get('finding')}\n\n"
        f"## Vulnerability Details\n"
        f"{f.get('synthesis', {}).get('analysis', f.get('finding'))}\n\n"
        f"## Proof of Concept / Verification\n"
        f"```solidity\n{poc[:2500]}\n```\n\n"
        f"---\n*Generated by ETH Hunter using Google Gemini AI Ultra*"
    )
    
    safe_name = repo.replace('/', '_')
    path = RESULTS_DIR / f"{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path.write_text(report)
    return {"report_path": str(path), "report": report}
